version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: lymych
          password: $DOCKER_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t lymych/circleci:$TAG .
          docker login -u lymych -p $DOCKER_PASSWORD
          docker push lymych/circleci:$TAG